### ISSUE TITLE
yun-express API access

### ISSUE THREAD

**Issue by hitesh1546** [dakalab/yun-express#1]
Hi,
How can i get $account, $secret?
Thanks

**Comment by hyperjiang** [comment]
You will need to register an account, it's not for free

**Comment by hitesh1546** [comment]
Where? Can you give me the link?

**Comment by hyperjiang** [comment]
https://www.yunexpress.com/ seems they have suspended registration for new users

**Comment by hitesh1546** [comment]
Thanks for the quick reply
